classdef visensor_imu < robotics.ros.Message
    %visensor_imu MATLAB implementation of visensor_msgs/visensor_imu
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2016 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'visensor_msgs/visensor_imu' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '2a6601ee1e26ed17ce49aea1dbd59920' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        GeometryMsgsQuaternionClass = robotics.ros.msg.internal.MessageFactory.getClassForType('geometry_msgs/Quaternion') % Dispatch to MATLAB class for message type geometry_msgs/Quaternion
        GeometryMsgsVector3Class = robotics.ros.msg.internal.MessageFactory.getClassForType('geometry_msgs/Vector3') % Dispatch to MATLAB class for message type geometry_msgs/Vector3
        StdMsgsHeaderClass = robotics.ros.msg.internal.MessageFactory.getClassForType('std_msgs/Header') % Dispatch to MATLAB class for message type std_msgs/Header
    end
    
    properties (Dependent)
        Header
        Orientation
        AngularVelocity
        LinearAcceleration
        Magnetometer
        Pressure
        Temperature
    end
    
    properties (Access = protected)
        Cache = struct('Header', [], 'Orientation', [], 'AngularVelocity', [], 'LinearAcceleration', [], 'Magnetometer', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'AngularVelocity', 'Header', 'LinearAcceleration', 'Magnetometer', 'Orientation', 'Pressure', 'Temperature'} % List of non-constant message properties
        ROSPropertyList = {'angular_velocity', 'header', 'linear_acceleration', 'magnetometer', 'orientation', 'pressure', 'temperature'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = visensor_imu(msg)
            %visensor_imu Construct the message object visensor_imu
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function header = get.Header(obj)
            %get.Header Get the value for property Header
            if isempty(obj.Cache.Header)
                obj.Cache.Header = feval(obj.StdMsgsHeaderClass, obj.JavaMessage.getHeader);
            end
            header = obj.Cache.Header;
        end
        
        function set.Header(obj, header)
            %set.Header Set the value for property Header
            validateattributes(header, {obj.StdMsgsHeaderClass}, {'nonempty', 'scalar'}, 'visensor_imu', 'header');
            
            obj.JavaMessage.setHeader(header.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Header)
                obj.Cache.Header.setJavaObject(header.getJavaObject);
            end
        end
        
        function orientation = get.Orientation(obj)
            %get.Orientation Get the value for property Orientation
            if isempty(obj.Cache.Orientation)
                obj.Cache.Orientation = feval(obj.GeometryMsgsQuaternionClass, obj.JavaMessage.getOrientation);
            end
            orientation = obj.Cache.Orientation;
        end
        
        function set.Orientation(obj, orientation)
            %set.Orientation Set the value for property Orientation
            validateattributes(orientation, {obj.GeometryMsgsQuaternionClass}, {'nonempty', 'scalar'}, 'visensor_imu', 'orientation');
            
            obj.JavaMessage.setOrientation(orientation.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Orientation)
                obj.Cache.Orientation.setJavaObject(orientation.getJavaObject);
            end
        end
        
        function angularvelocity = get.AngularVelocity(obj)
            %get.AngularVelocity Get the value for property AngularVelocity
            if isempty(obj.Cache.AngularVelocity)
                obj.Cache.AngularVelocity = feval(obj.GeometryMsgsVector3Class, obj.JavaMessage.getAngularVelocity);
            end
            angularvelocity = obj.Cache.AngularVelocity;
        end
        
        function set.AngularVelocity(obj, angularvelocity)
            %set.AngularVelocity Set the value for property AngularVelocity
            validateattributes(angularvelocity, {obj.GeometryMsgsVector3Class}, {'nonempty', 'scalar'}, 'visensor_imu', 'angularvelocity');
            
            obj.JavaMessage.setAngularVelocity(angularvelocity.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.AngularVelocity)
                obj.Cache.AngularVelocity.setJavaObject(angularvelocity.getJavaObject);
            end
        end
        
        function linearacceleration = get.LinearAcceleration(obj)
            %get.LinearAcceleration Get the value for property LinearAcceleration
            if isempty(obj.Cache.LinearAcceleration)
                obj.Cache.LinearAcceleration = feval(obj.GeometryMsgsVector3Class, obj.JavaMessage.getLinearAcceleration);
            end
            linearacceleration = obj.Cache.LinearAcceleration;
        end
        
        function set.LinearAcceleration(obj, linearacceleration)
            %set.LinearAcceleration Set the value for property LinearAcceleration
            validateattributes(linearacceleration, {obj.GeometryMsgsVector3Class}, {'nonempty', 'scalar'}, 'visensor_imu', 'linearacceleration');
            
            obj.JavaMessage.setLinearAcceleration(linearacceleration.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.LinearAcceleration)
                obj.Cache.LinearAcceleration.setJavaObject(linearacceleration.getJavaObject);
            end
        end
        
        function magnetometer = get.Magnetometer(obj)
            %get.Magnetometer Get the value for property Magnetometer
            if isempty(obj.Cache.Magnetometer)
                obj.Cache.Magnetometer = feval(obj.GeometryMsgsVector3Class, obj.JavaMessage.getMagnetometer);
            end
            magnetometer = obj.Cache.Magnetometer;
        end
        
        function set.Magnetometer(obj, magnetometer)
            %set.Magnetometer Set the value for property Magnetometer
            validateattributes(magnetometer, {obj.GeometryMsgsVector3Class}, {'nonempty', 'scalar'}, 'visensor_imu', 'magnetometer');
            
            obj.JavaMessage.setMagnetometer(magnetometer.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Magnetometer)
                obj.Cache.Magnetometer.setJavaObject(magnetometer.getJavaObject);
            end
        end
        
        function pressure = get.Pressure(obj)
            %get.Pressure Get the value for property Pressure
            pressure = double(obj.JavaMessage.getPressure);
        end
        
        function set.Pressure(obj, pressure)
            %set.Pressure Set the value for property Pressure
            validateattributes(pressure, {'numeric'}, {'nonempty', 'scalar'}, 'visensor_imu', 'pressure');
            
            obj.JavaMessage.setPressure(pressure);
        end
        
        function temperature = get.Temperature(obj)
            %get.Temperature Get the value for property Temperature
            temperature = double(obj.JavaMessage.getTemperature);
        end
        
        function set.Temperature(obj, temperature)
            %set.Temperature Set the value for property Temperature
            validateattributes(temperature, {'numeric'}, {'nonempty', 'scalar'}, 'visensor_imu', 'temperature');
            
            obj.JavaMessage.setTemperature(temperature);
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Header = [];
            obj.Cache.Orientation = [];
            obj.Cache.AngularVelocity = [];
            obj.Cache.LinearAcceleration = [];
            obj.Cache.Magnetometer = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Pressure = obj.Pressure;
            cpObj.Temperature = obj.Temperature;
            
            % Recursively copy compound properties
            cpObj.Header = copy(obj.Header);
            cpObj.Orientation = copy(obj.Orientation);
            cpObj.AngularVelocity = copy(obj.AngularVelocity);
            cpObj.LinearAcceleration = copy(obj.LinearAcceleration);
            cpObj.Magnetometer = copy(obj.Magnetometer);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Pressure = strObj.Pressure;
            obj.Temperature = strObj.Temperature;
            obj.Header = feval([obj.StdMsgsHeaderClass '.loadobj'], strObj.Header);
            obj.Orientation = feval([obj.GeometryMsgsQuaternionClass '.loadobj'], strObj.Orientation);
            obj.AngularVelocity = feval([obj.GeometryMsgsVector3Class '.loadobj'], strObj.AngularVelocity);
            obj.LinearAcceleration = feval([obj.GeometryMsgsVector3Class '.loadobj'], strObj.LinearAcceleration);
            obj.Magnetometer = feval([obj.GeometryMsgsVector3Class '.loadobj'], strObj.Magnetometer);
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Pressure = obj.Pressure;
            strObj.Temperature = obj.Temperature;
            strObj.Header = saveobj(obj.Header);
            strObj.Orientation = saveobj(obj.Orientation);
            strObj.AngularVelocity = saveobj(obj.AngularVelocity);
            strObj.LinearAcceleration = saveobj(obj.LinearAcceleration);
            strObj.Magnetometer = saveobj(obj.Magnetometer);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.visensor_msgs.visensor_imu.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.visensor_msgs.visensor_imu;
            obj.reload(strObj);
        end
    end
end
